### ISSUE TITLE
Cannto get promptConfirm to work both in IntelliJ and iTerm

### ISSUE THREAD

**Issue by Essay97** [YanivGrama/kotlin-inquirer#18]
I am using kotlin-inquirer on a Mac with IntelliJ Idea Community. 
I have this simple snippet:
```kotlin
fun main(args: Array<String>) {
    val itsOk: Boolean = KInquirer.promptConfirm("Is it ok today?")
    println("Today is ${if (itsOk) "" else "not"} ok")
}
```
When I run it by pressing the "play" button on IntelliJ, I get the prompt but pressing the arrow keys simply does nothing. Also when I try to simply press enter I get prompted again. 
If I try to run it on iTerm via `./gradlew run` i get the following error:
```
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
? Is it ok today?  Yes [No]Exception in thread "main" java.lang.IllegalArgumentException: Invalid Char code: -1
        at com.github.kinquirer.core.KInquirerReaderHandlerNewTerminal.handleInteraction(ReaderHandler.kt:28)
        at com.github.kinquirer.KInquirer$prompt$1.invoke(KInquirer.kt:17)
        at com.github.kinquirer.KInquirer$prompt$1.invoke(KInquirer.kt:13)
        at com.github.kinquirer.KInquirer.runTerminal(KInquirer.kt:33)
        at com.github.kinquirer.KInquirer.prompt(KInquirer.kt:13)
        at com.github.kinquirer.components.ConfirmKt.promptConfirm(Confirm.kt:56)
        at com.github.kinquirer.components.ConfirmKt.promptConfirm$default(Confirm.kt:52)
        at MainKt.main(Main.kt:22)
```

What am I missing?

**Comment by vsigler** [comment]
I've also bumped into this and this is a problem, or rather limitation of the jline library.
See here: https://stackoverflow.com/questions/69247723/cannot-create-os-terminal-with-jline3

When I build a jar and run just using `java -jar myapp.jar`, it works as expected. Too bad I needed it as a part of a gradle build to query for some stuff, where it does not seem to work.
